/*
 * To change this license header, choose License Headers in Project Propert    return null; //To change body of generated lambdas, choose Tools | Templates.
ies.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulguipbo;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import komponen.TableHeaderBorder;


/**
 *
 * @author Cahya Robbi
 */
public class ModulGuiPboFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModulGuiPboFrame
     */
    public ModulGuiPboFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etNamaMakanan = new komponen.RoundTextField(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        etJenisMakanan = new komponen.RoundTextField(15);
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kalori = new komponen.RoundTextField(15);
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        ratingSatu = new javax.swing.JRadioButton();
        ratingDua = new javax.swing.JRadioButton();
        ratingTiga = new javax.swing.JRadioButton();
        btnDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(34, 34, 34));

        jPanel1.setBackground(new java.awt.Color(41, 38, 67));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Makanan");
        jLabel1.setToolTipText("");

        etNamaMakanan.setBackground(new java.awt.Color(51, 51, 77));
        etNamaMakanan.setForeground(new java.awt.Color(255, 255, 255));
        etNamaMakanan.setBorder(null);
        etNamaMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNamaMakananActionPerformed(evt);
            }
        });
        etNamaMakanan.setBorder(BorderFactory.createCompoundBorder(
            etNamaMakanan.getBorder(),
            BorderFactory.createEmptyBorder(5, 20, 5, 5)));

    TableCellRenderer baseRenderer = jTable1.getTableHeader().getDefaultRenderer();
    jTable1.setBackground(new java.awt.Color(28, 26, 48));
    jTable1.getTableHeader().setBackground(new java.awt.Color(51,51,77));
    jTable1.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
    jTable1.setFillsViewportHeight(true);
    jTable1.getTableHeader().setPreferredSize(new Dimension(15, 30));
    jTable1.setForeground(new java.awt.Color(255, 255, 255));
    jTable1.getTableHeader().setDefaultRenderer(new TableHeaderBorder(baseRenderer));
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Nama Makanan", "Jenis Makanan", "Rating", "Kalori"
        }
    ));
    TableColumnModel tcm = jTable1.getColumnModel();
    tcm.removeColumn( tcm.getColumn(3) );
    tcm.removeColumn( tcm.getColumn(1) );
    jTable1.setOpaque(false);
    jScrollPane1.setViewportView(jTable1);

    etJenisMakanan.setBackground(new java.awt.Color(51, 51, 77));
    etJenisMakanan.setForeground(new java.awt.Color(255, 255, 255));
    etJenisMakanan.setBorder(null);
    etJenisMakanan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            etJenisMakananActionPerformed(evt);
        }
    });
    etJenisMakanan.setBorder(BorderFactory.createCompoundBorder(
        etJenisMakanan.getBorder(),
        BorderFactory.createEmptyBorder(5, 20, 5, 5)));

jPanel2.setBackground(new java.awt.Color(28, 26, 48));

jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
jLabel2.setForeground(new java.awt.Color(255, 255, 255));
jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
jLabel2.setText("Makanan Favorit");

javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addComponent(jLabel2)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(25, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addGap(24, 24, 24))
    );

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Jenis Makanan");
    jLabel3.setToolTipText("");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Rating");
    jLabel4.setToolTipText("");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Jumlah Kalori");
    jLabel5.setToolTipText("");

    kalori.setBackground(new java.awt.Color(51, 51, 77));
    kalori.setForeground(new java.awt.Color(255, 255, 255));
    kalori.setBorder(null);
    kalori.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            kaloriActionPerformed(evt);
        }
    });
    kalori.setBorder(BorderFactory.createCompoundBorder(
        kalori.getBorder(),
        BorderFactory.createEmptyBorder(5, 20, 5, 5)));

btnTambah.setText("TAMBAH");
btnTambah.setBackground(new Color(66,208,196));
btnTambah.setForeground(Color.WHITE);
btnTambah.setBorderPainted(false);
btnTambah.setFocusPainted(true);
btnTambah.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTambahActionPerformed(evt);
    }
    });

    btnBatal.setBackground(new Color(221,139,81));
    btnBatal.setForeground(new java.awt.Color(255, 255, 255));
    btnBatal.setText("BATAL");
    btnBatal.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBatalActionPerformed(evt);
        }
    });

    buttonGroup1.add(ratingSatu);
    ratingSatu.setForeground(new java.awt.Color(255, 255, 255));
    ratingSatu.setText("1");
    ratingSatu.setOpaque(false);

    buttonGroup1.add(ratingDua);
    ratingDua.setForeground(new java.awt.Color(255, 255, 255));
    ratingDua.setText("2");
    ratingDua.setOpaque(false);

    buttonGroup1.add(ratingTiga);
    ratingTiga.setForeground(new java.awt.Color(255, 255, 255));
    ratingTiga.setText("3");
    ratingTiga.setOpaque(false);

    btnBatal.setBackground(new Color(221,139,81));
    btnDetail.setText("DETAIL");
    btnDetail.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDetailActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etNamaMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(etJenisMakanan)
                                .addComponent(kalori)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ratingSatu)
                                    .addGap(18, 18, 18)
                                    .addComponent(ratingDua)
                                    .addGap(18, 18, 18)
                                    .addComponent(ratingTiga))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnTambah)
                            .addGap(18, 18, 18)
                            .addComponent(btnBatal)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnDetail)
            .addGap(25, 25, 25))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(51, 51, 51)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(etNamaMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(etJenisMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(ratingSatu)
                .addComponent(ratingDua)
                .addComponent(ratingTiga))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(kalori, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnTambah)
                .addComponent(btnBatal))
            .addGap(59, 59, 59)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnDetail)
            .addContainerGap(30, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etNamaMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNamaMakananActionPerformed
      
    }//GEN-LAST:event_etNamaMakananActionPerformed

    private void etJenisMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etJenisMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etJenisMakananActionPerformed

    private void kaloriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaloriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaloriActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String rating ="";
        if(ratingSatu.isSelected()){
            rating = "1";
        }
        else if(ratingDua.isSelected()){
            rating = "2";
        }
        else if(ratingTiga.isSelected()){
            rating = "3";
        }
        String data [] = {etNamaMakanan.getText(),etJenisMakanan.getText(),rating,kalori.getText()};
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(data);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       etJenisMakanan.setText("");
       etNamaMakanan.setText("");
       buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        int indexRow = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        String messege = "nama Makanan : "+model.getValueAt(indexRow,0)+"\nJenis Makanan : "+model.getValueAt(indexRow,1)+"\nRating :"+model.getValueAt(indexRow,2)+"\nKalori : "+model.getValueAt(indexRow,3);
        JOptionPane.showMessageDialog(this, messege);
    }//GEN-LAST:event_btnDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModulGuiPboFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModulGuiPboFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModulGuiPboFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModulGuiPboFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModulGuiPboFrame().setVisible(true);
               }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JTextField etJenisMakanan;
    private static javax.swing.JTextField etNamaMakanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private static javax.swing.JTextField kalori;
    private javax.swing.JRadioButton ratingDua;
    private javax.swing.JRadioButton ratingSatu;
    private javax.swing.JRadioButton ratingTiga;
    // End of variables declaration//GEN-END:variables
}
